<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Adicionar descontos ao pedido</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c5864f03-64c5-44d2-853e-81f5adb8dd21</testSuiteGuid>
   <testCaseLink>
      <guid>ac317606-2dde-4195-ad90-c146076cc394</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04- Adicionar descontos ao pedido</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>61aacce3-12f8-4850-8f8b-fa01471f7d02</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Adicionar descontos ao pedido</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f743a23-4e73-402a-8b50-bdc4c8b6ffd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf776ae1-90eb-4227-a6e2-61068424c6b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f2c3658-978b-47e5-a379-b96c25100484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1538728-8da4-4c20-8ffe-b910f7e4e23b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
