<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_485a4171-3e90-4043-ae52-e67_f5dd22</name>
   <tag></tag>
   <elementGuidId>a7a14d41-d873-44e4-8a87-2aaa080d80d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ba8efb62-c4b1-45b4-9593-adf96161f9cb</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;1f69d189-f1ff-4c39-8807-c0af0605b527&quot;][count(. | //*[@id = '485a4171-3e90-4043-ae52-e670a0a4736f']) = count(//*[@id = '485a4171-3e90-4043-ae52-e670a0a4736f'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='485a4171-3e90-4043-ae52-e670a0a4736f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>485a4171-3e90-4043-ae52-e670a0a4736f</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;1f69d189-f1ff-4c39-8807-c0af0605b527&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='485a4171-3e90-4043-ae52-e670a0a4736f']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '485a4171-3e90-4043-ae52-e670a0a4736f']</value>
   </webElementXpaths>
</WebElementEntity>
