<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_54464be8-8a06-4dbc-aff8-040_d41b49</name>
   <tag></tag>
   <elementGuidId>006b43df-b08c-4e6c-9a6c-cefd5c0e008d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>#e36a2df5-ef1b-4eff-92a8-ed0dc80c7fc3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#54464be8-8a06-4dbc-aff8-040bb6e0319e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>54464be8-8a06-4dbc-aff8-040bb6e0319e</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;54464be8-8a06-4dbc-aff8-040bb6e0319e&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;e36a2df5-ef1b-4eff-92a8-ed0dc80c7fc3&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '54464be8-8a06-4dbc-aff8-040bb6e0319e']</value>
   </webElementXpaths>
</WebElementEntity>
